
"""
Alert database model for LabGuardian AI.

This module defines the SQLAlchemy model used to
store laboratory alerts.

Alerts can be generated when the system detects:

- Abnormal temperature
- Excessive transport time
- Processing delays
- Storage problems
- Sample degradation risk
- Equipment anomalies
- Machine Learning anomalies
"""

from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class Alert(Base):
    """
    Represents an alert generated by LabGuardian AI.
    """

    __tablename__ = "alerts"

    # ─────────────────────────────────────────────
    # Primary key
    # ─────────────────────────────────────────────

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        index=True,
        autoincrement=True,
    )

    # ─────────────────────────────────────────────
    # Sample relationship
    # ─────────────────────────────────────────────

    sample_id: Mapped[int | None] = mapped_column(
        ForeignKey(
            "samples.id",
            ondelete="SET NULL",
        ),
        nullable=True,
        index=True,
    )

    sample_code: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
        index=True,
    )

    # ─────────────────────────────────────────────
    # Alert information
    # ─────────────────────────────────────────────

    alert_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
    )

    severity: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="MEDIUM",
        index=True,
    )

    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="ACTIVE",
        index=True,
    )

    title: Mapped[str] = mapped_column(
        String(150),
        nullable=False,
    )

    message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    # ─────────────────────────────────────────────
    # Risk information
    # ─────────────────────────────────────────────

    risk_score: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    # ─────────────────────────────────────────────
    # Source
    # ─────────────────────────────────────────────

    source: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="SYSTEM",
    )

    # ─────────────────────────────────────────────
    # Resolution
    # ─────────────────────────────────────────────

    resolved_by: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
    )

    resolution_notes: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # ─────────────────────────────────────────────
    # Dates
    # ─────────────────────────────────────────────

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        nullable=False,
        index=True,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )

    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # ─────────────────────────────────────────────
    # Serialization
    # ─────────────────────────────────────────────

    def to_dict(self) -> dict[str, Any]:
        """
        Converts the alert model into a dictionary.
        """

        return {
            "id": self.id,
            "sample_id": self.sample_id,
            "sample_code": self.sample_code,
            "alert_type": self.alert_type,
            "severity": self.severity,
            "status": self.status,
            "title": self.title,
            "message": self.message,
            "risk_score": self.risk_score,
            "source": self.source,
            "resolved_by": self.resolved_by,
            "resolution_notes": self.resolution_notes,
            "created_at": (
                self.created_at.isoformat()
                if self.created_at
                else None
            ),
            "updated_at": (
                self.updated_at.isoformat()
                if self.updated_at
                else None
            ),
            "resolved_at": (
                self.resolved_at.isoformat()
                if self.resolved_at
                else None
            ),
        }

    def __repr__(self) -> str:
        return (
            f"<Alert("
            f"id={self.id}, "
            f"sample_code={self.sample_code!r}, "
            f"type={self.alert_type!r}, "
            f"severity={self.severity!r}, "
            f"status={self.status!r}"
            f")>"
        )

